### ISSUE TITLE
No such file or directory: 'wiki_entity_calc.pickle'

### ISSUE THREAD

**Issue by Jorigorn** [machinereading/eld-2018#1]
Hi, thanks for sharing the code, but where can I get this file?
No such file or directory: 'wiki_entity_calc.pickle' 

(mulrel-nel) ➜  eld-2018 git:(master) ✗ python3 -u -m nel.main --mode train --n_rels 3 --mulrel_type ment-norm
Traceback (most recent call last):
  File "/home/John/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/John/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hdd/experiments/John/eld-2018/nel/main.py", line 4, in <module>
    from nel.etri import make_text_into_conll, etri_into_conll
  File "/mnt/hdd/experiments/John/eld-2018/nel/etri.py", line 6, in <module>
    from nel.crowdsourcing_preprocessor import candidates
  File "/mnt/hdd/experiments/John/eld-2018/nel/crowdsourcing_preprocessor.py", line 13, in <module>
    with open("wiki_entity_calc.pickle", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wiki_entity_calc.pickle'

Could you please, write more, how this is different from original model?
John
Thanks.

**Comment by hongmae1102** [comment]
Hi, thanks for sharing the code, I had the same issue as "John".
Could you please, write more, how this is different from original model?

---------------------------------------------------------------------------------------
FileNotFoundError: [Errno 2] No such file or directory: 'wiki_entity_calc.pickle'

hmshen
Thanks.
